[package]
name = "data_struct"
version = "0.1.0"
authors = ["Jack <920491071@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
